<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ["name" => "Afghanistan", "code" => "AFG", "active" => true],
            ["name" => "Albania", "code" => "ALB", "active" => true],
            ["name" => "Algeria", "code" => "DZA", "active" => true],
            ["name" => "American Samoa", "code" => "ASM", "active" => true],
            ["name" => "Andorra", "code" => "AND", "active" => true],
            ["name" => "Angola", "code" => "AGO", "active" => true],
            ["name" => "Anguilla", "code" => "AIA", "active" => true],
            ["name" => "Antarctica", "code" => "ATA", "active" => true],
            ["name" => "Antigua and Barbuda", "code" => "ATG", "active" => true],
            ["name" => "Argentina", "code" => "ARG", "active" => true],
            ["name" => "Armenia", "code" => "ARM", "active" => true],
            ["name" => "Aruba", "code" => "ABW", "active" => true],
            ["name" => "Australia", "code" => "AUS", "active" => true],
            ["name" => "Austria", "code" => "AUT", "active" => true],
            ["name" => "Azerbaijan", "code" => "AZE", "active" => true],
            ["name" => "Bahamas", "code" => "BHS", "active" => true],
            ["name" => "Bahrain", "code" => "BHR", "active" => true],
            ["name" => "Bangladesh", "code" => "BGD", "active" => true],
            ["name" => "Barbados", "code" => "BRB", "active" => true],
            ["name" => "Belarus", "code" => "BLR", "active" => true],
            ["name" => "Belgium", "code" => "BEL", "active" => true],
            ["name" => "Belize", "code" => "BLZ", "active" => true],
            ["name" => "Benin", "code" => "BEN", "active" => true],
            ["name" => "Bermuda", "code" => "BMU", "active" => true],
            ["name" => "Bhutan", "code" => "BTN", "active" => true],
            ["name" => "Bolivia", "code" => "BOL", "active" => true],
            ["name" => "Bosnia and Herzegovina", "code" => "BIH", "active" => true],
            ["name" => "Botswana", "code" => "BWA", "active" => true],
            ["name" => "Bouvet Island", "code" => "BVT", "active" => true],
            ["name" => "Brazil", "code" => "BRA", "active" => true],
            ["name" => "British Antarctic Territory", "code" => "BES", "active" => true],
            ["name" => "British Indian Ocean Territory", "code" => "IOT", "active" => true],
            ["name" => "British Virgin Islands", "code" => "VGB", "active" => true],
            ["name" => "Brunei", "code" => "BRN", "active" => true],
            ["name" => "Bulgaria", "code" => "BGR", "active" => true],
            ["name" => "Burkina Faso", "code" => "BFA", "active" => true],
            ["name" => "Burundi", "code" => "BDI", "active" => true],
            ["name" => "Cambodia", "code" => "KHM", "active" => true],
            ["name" => "Cameroon", "code" => "CMR", "active" => true],
            ["name" => "Canada", "code" => "CAN", "active" => true],
            ["name" => "Canton and Enderbury Islands", "code" => "CTE", "active" => true],
            ["name" => "Cape Verde", "code" => "CPV", "active" => true],
            ["name" => "Cayman Islands", "code" => "CYM", "active" => true],
            ["name" => "Central African Republic", "code" => "CAF", "active" => true],
            ["name" => "Chad", "code" => "TCD", "active" => true],
            ["name" => "Chile", "code" => "CHL", "active" => true],
            ["name" => "China", "code" => "CHN", "active" => true],
            ["name" => "Christmas Island", "code" => "CXR", "active" => true],
            ["name" => "Cocos [Keeling] Islands", "code" => "CCK", "active" => true],
            ["name" => "Colombia", "code" => "COL", "active" => true],
            ["name" => "Comoros", "code" => "COM", "active" => true],
            ["name" => "Congo - Brazzaville", "code" => "COG", "active" => true],
            ["name" => "Congo - Kinshasa", "code" => "COD", "active" => true],
            ["name" => "Cook Islands", "code" => "COK", "active" => true],
            ["name" => "Costa Rica", "code" => "CRI", "active" => true],
            ["name" => "Croatia", "code" => "HRV", "active" => true],
            ["name" => "Cuba", "code" => "CUB", "active" => true],
            ["name" => "Curaçao", "code" => "CUW", "active" => true],
            ["name" => "Cyprus", "code" => "CYP", "active" => true],
            ["name" => "Czech Republic", "code" => "CZE", "active" => true],
            ["name" => "Côte d'Ivoire", "code" => "CIV", "active" => true],
            ["name" => "Denmark", "code" => "DNK", "active" => true],
            ["name" => "Djibouti", "code" => "DJI", "active" => true],
            ["name" => "Dominica", "code" => "DMA", "active" => true],
            ["name" => "Dominican Republic", "code" => "DOM", "active" => true],
            ["name" => "Dronning Maud Land", "code" => "ATN", "active" => true],
            ["name" => "Ecuador", "code" => "ECU", "active" => true],
            ["name" => "Egypt", "code" => "EGY", "active" => true],
            ["name" => "El Salvador", "code" => "SLV", "active" => true],
            ["name" => "Equatorial Guinea", "code" => "GNQ", "active" => true],
            ["name" => "Eritrea", "code" => "ERI", "active" => true],
            ["name" => "Estonia", "code" => "EST", "active" => true],
            ["name" => "Ethiopia", "code" => "ETH", "active" => true],
            ["name" => "Falkland Islands", "code" => "FLK", "active" => true],
            ["name" => "Faroe Islands", "code" => "FRO", "active" => true],
            ["name" => "Fiji", "code" => "FJI", "active" => true],
            ["name" => "Finland", "code" => "FIN", "active" => true],
            ["name" => "France", "code" => "FRA", "active" => true],
            ["name" => "French Guiana", "code" => "GUF", "active" => true],
            ["name" => "French Polynesia", "code" => "PYF", "active" => true],
            ["name" => "French Southern Territories", "code" => "ATF", "active" => true],
            ["name" => "French Southern and Antarctic Territories", "code" => "ATF2", "active" => true],
            ["name" => "Gabon", "code" => "GAB", "active" => true],
            ["name" => "Gambia", "code" => "GMB", "active" => true],
            ["name" => "Georgia", "code" => "GEO", "active" => true],
            ["name" => "Germany", "code" => "DEU", "active" => true],
            ["name" => "Ghana", "code" => "GHA", "active" => true],
            ["name" => "Gibraltar", "code" => "GIB", "active" => true],
            ["name" => "Greece", "code" => "GRC", "active" => true],
            ["name" => "Greenland", "code" => "GRL", "active" => true],
            ["name" => "Grenada", "code" => "GRD", "active" => true],
            ["name" => "Guadeloupe", "code" => "GLP", "active" => true],
            ["name" => "Guam", "code" => "GUM", "active" => true],
            ["name" => "Guatemala", "code" => "GTM", "active" => true],
            ["name" => "Guernsey", "code" => "GGY", "active" => true],
            ["name" => "Guinea", "code" => "GIN", "active" => true],
            ["name" => "Guinea-Bissau", "code" => "GNB", "active" => true],
            ["name" => "Guyana", "code" => "GUY", "active" => true],
            ["name" => "Haiti", "code" => "HTI", "active" => true],
            ["name" => "Heard Island and McDonald Islands", "code" => "HMD", "active" => true],
            ["name" => "Honduras", "code" => "HND", "active" => true],
            ["name" => "Hong Kong SAR China", "code" => "HKG", "active" => true],
            ["name" => "Hungary", "code" => "HUN", "active" => true],
            ["name" => "Iceland", "code" => "ISL", "active" => true],
            ["name" => "India", "code" => "IND", "active" => true],
            ["name" => "Indonesia", "code" => "IDN", "active" => true],
            ["name" => "Iran", "code" => "IRN", "active" => true],
            ["name" => "Iraq", "code" => "IRQ", "active" => true],
            ["name" => "Ireland", "code" => "IRL", "active" => true],
            ["name" => "Isle of Man", "code" => "IMN", "active" => true],
            ["name" => "Israel", "code" => "ISR", "active" => true],
            ["name" => "Italy", "code" => "ITA", "active" => true],
            ["name" => "Jamaica", "code" => "JAM", "active" => true],
            ["name" => "Japan", "code" => "JPN", "active" => true],
            ["name" => "Jersey", "code" => "JEY", "active" => true],
            ["name" => "Johnston Island", "code" => "JTN", "active" => true],
            ["name" => "Jordan", "code" => "JOR", "active" => true],
            ["name" => "Kazakhstan", "code" => "KAZ", "active" => true],
            ["name" => "Kenya", "code" => "KEN", "active" => true],
            ["name" => "Kiribati", "code" => "KIR", "active" => true],
            ["name" => "Kuwait", "code" => "KWT", "active" => true],
            ["name" => "Kyrgyzstan", "code" => "KGZ", "active" => true],
            ["name" => "Laos", "code" => "LAO", "active" => true],
            ["name" => "Latvia", "code" => "LVA", "active" => true],
            ["name" => "Lebanon", "code" => "LBN", "active" => true],
            ["name" => "Lesotho", "code" => "LSO", "active" => true],
            ["name" => "Liberia", "code" => "LBR", "active" => true],
            ["name" => "Libya", "code" => "LBY", "active" => true],
            ["name" => "Liechtenstein", "code" => "LIE", "active" => true],
            ["name" => "Lithuania", "code" => "LTU", "active" => true],
            ["name" => "Luxembourg", "code" => "LUX", "active" => true],
            ["name" => "Macau SAR China", "code" => "MAC", "active" => true],
            ["name" => "Macedonia", "code" => "MKD", "active" => true],
            ["name" => "Madagascar", "code" => "MDG", "active" => true],
            ["name" => "Malawi", "code" => "MWI", "active" => true],
            ["name" => "Malaysia", "code" => "MYS", "active" => true],
            ["name" => "Maldives", "code" => "MDV", "active" => true],
            ["name" => "Mali", "code" => "MLI", "active" => true],
            ["name" => "Malta", "code" => "MLT", "active" => true],
            ["name" => "Marshall Islands", "code" => "MHL", "active" => true],
            ["name" => "Martinique", "code" => "MTQ", "active" => true],
            ["name" => "Mauritania", "code" => "MRT", "active" => true],
            ["name" => "Mauritius", "code" => "MUS", "active" => true],
            ["name" => "Mayotte", "code" => "MYT", "active" => true],
            ["name" => "Metropolitan France", "code" => "FXX", "active" => true],
            ["name" => "Mexico", "code" => "MEX", "active" => true],
            ["name" => "Micronesia", "code" => "FSM", "active" => true],
            ["name" => "Midway Islands", "code" => "MID", "active" => true],
            ["name" => "Moldova", "code" => "MDA", "active" => true],
            ["name" => "Monaco", "code" => "MCO", "active" => true],
            ["name" => "Mongolia", "code" => "MNG", "active" => true],
            ["name" => "Montenegro", "code" => "MNE", "active" => true],
            ["name" => "Montserrat", "code" => "MSR", "active" => true],
            ["name" => "Morocco", "code" => "MAR", "active" => true],
            ["name" => "Mozambique", "code" => "MOZ", "active" => true],
            ["name" => "Myanmar [Burma]", "code" => "MMR", "active" => true],
            ["name" => "Namibia", "code" => "NAM", "active" => true],
            ["name" => "Nauru", "code" => "NRU", "active" => true],
            ["name" => "Nepal", "code" => "NPL", "active" => true],
            ["name" => "Netherlands", "code" => "NLD", "active" => true],
            ["name" => "Netherlands Antilles", "code" => "ANT", "active" => true],
            ["name" => "Neutral Zone", "code" => "NTZ", "active" => true],
            ["name" => "New Caledonia", "code" => "NCL", "active" => true],
            ["name" => "New Zealand", "code" => "NZL", "active" => true],
            ["name" => "Nicaragua", "code" => "NIC", "active" => true],
            ["name" => "Niger", "code" => "NER", "active" => true],
            ["name" => "Nigeria", "code" => "NGA", "active" => true],
            ["name" => "Niue", "code" => "NIU", "active" => true],
            ["name" => "Norfolk Island", "code" => "NFK", "active" => true],
            ["name" => "North Korea", "code" => "PRK", "active" => true],
            ["name" => "North Vietnam", "code" => "VDR", "active" => true],
            ["name" => "Northern Mariana Islands", "code" => "MNP", "active" => true],
            ["name" => "Norway", "code" => "NOR", "active" => true],
            ["name" => "Oman", "code" => "OMN", "active" => true],
            ["name" => "Other", "code" => "OT", "active" => false],
            ["name" => "Pacific Islands Trust Territory", "code" => "PCI", "active" => true],
            ["name" => "Pakistan", "code" => "PAK", "active" => true],
            ["name" => "Palau", "code" => "PLW", "active" => true],
            ["name" => "Palestinian Territories", "code" => "PSE", "active" => true],
            ["name" => "Panama", "code" => "PAN", "active" => true],
            ["name" => "Panama Canal Zone", "code" => "PCZ", "active" => true],
            ["name" => "Papua New Guinea", "code" => "PNG", "active" => true],
            ["name" => "Paraguay", "code" => "PRY", "active" => true],
            ["name" => "Peru", "code" => "PER", "active" => true],
            ["name" => "Philippines", "code" => "PHL", "active" => true],
            ["name" => "Pitcairn Islands", "code" => "PCN", "active" => true],
            ["name" => "Poland", "code" => "POL", "active" => true],
            ["name" => "Portugal", "code" => "PRT", "active" => true],
            ["name" => "Puerto Rico", "code" => "PRI", "active" => true],
            ["name" => "Qatar", "code" => "QAT", "active" => true],
            ["name" => "Romania", "code" => "ROU", "active" => true],
            ["name" => "Russia", "code" => "RUS", "active" => true],
            ["name" => "Rwanda", "code" => "RWA", "active" => true],
            ["name" => "Réunion", "code" => "REU", "active" => true],
            ["name" => "Saint Barthélemy", "code" => "BLM", "active" => true],
            ["name" => "Saint Helena", "code" => "SHN", "active" => true],
            ["name" => "Saint Kitts and Nevis", "code" => "KNA", "active" => true],
            ["name" => "Saint Lucia", "code" => "LCA", "active" => true],
            ["name" => "Saint Martin", "code" => "MAF", "active" => true],
            ["name" => "Saint Pierre and Miquelon", "code" => "SPM", "active" => true],
            ["name" => "Saint Vincent and the Grenadines", "code" => "VCT", "active" => true],
            ["name" => "Samoa", "code" => "WSM", "active" => true],
            ["name" => "San Marino", "code" => "SMR", "active" => true],
            ["name" => "Saudi Arabia", "code" => "SAU", "active" => true],
            ["name" => "Senegal", "code" => "SEN", "active" => true],
            ["name" => "Serbia", "code" => "SRB", "active" => true],
            ["name" => "Serbia and Montenegro", "code" => "SCG", "active" => true],
            ["name" => "Seychelles", "code" => "SYC", "active" => true],
            ["name" => "Sierra Leone", "code" => "SLE", "active" => true],
            ["name" => "Singapore", "code" => "SGP", "active" => true],
            ["name" => "Slovakia", "code" => "SVK", "active" => true],
            ["name" => "Slovenia", "code" => "SVN", "active" => true],
            ["name" => "Solomon Islands", "code" => "SLB", "active" => true],
            ["name" => "Somalia", "code" => "SOM", "active" => true],
            ["name" => "South Africa", "code" => "ZAF", "active" => true],
            ["name" => "South Georgia and the South Sandwich Islands", "code" => "SGS", "active" => true],
            ["name" => "South Korea", "code" => "KOR", "active" => true],
            ["name" => "Spain", "code" => "ESP", "active" => true],
            ["name" => "Sri Lanka", "code" => "LKA", "active" => true],
            ["name" => "Sudan", "code" => "SDN", "active" => true],
            ["name" => "Suriname", "code" => "SUR", "active" => true],
            ["name" => "Svalbard and Jan Mayen", "code" => "SJM", "active" => true],
            ["name" => "Swaziland", "code" => "SWZ", "active" => true],
            ["name" => "Sweden", "code" => "SWE", "active" => true],
            ["name" => "Switzerland", "code" => "CHE", "active" => true],
            ["name" => "Syria", "code" => "SYR", "active" => true],
            ["name" => "São Tomé and Príncipe", "code" => "STP", "active" => true],
            ["name" => "Taiwan", "code" => "TWN", "active" => true],
            ["name" => "Tajikistan", "code" => "TJK", "active" => true],
            ["name" => "Tanzania", "code" => "TZA", "active" => true],
            ["name" => "Thailand", "code" => "THA", "active" => true],
            ["name" => "Timor-Leste", "code" => "TLS", "active" => true],
            ["name" => "Togo", "code" => "TGO", "active" => true],
            ["name" => "Tokelau", "code" => "TKL", "active" => true],
            ["name" => "Tonga", "code" => "TON", "active" => true],
            ["name" => "Trinidad and Tobago", "code" => "TTO", "active" => true],
            ["name" => "Tunisia", "code" => "TUN", "active" => true],
            ["name" => "Turkey", "code" => "TUR", "active" => true],
            ["name" => "Turkmenistan", "code" => "TKM", "active" => true],
            ["name" => "Turks and Caicos Islands", "code" => "TCA", "active" => true],
            ["name" => "Tuvalu", "code" => "TUV", "active" => true],
            ["name" => "U.S. Minor Outlying Islands", "code" => "UMI", "active" => true],
            ["name" => "U.S. Miscellaneous Pacific Islands", "code" => "PUS", "active" => true],
            ["name" => "U.S. Virgin Islands", "code" => "VIR", "active" => true],
            ["name" => "Uganda", "code" => "UGA", "active" => true],
            ["name" => "Ukraine", "code" => "UKR", "active" => true],
            ["name" => "Union of Soviet Socialist Republics", "code" => "???", "active" => true],
            ["name" => "United Arab Emirates", "code" => "ARE", "active" => true],
            ["name" => "United Kingdom", "code" => "GBR", "active" => true],
            ["name" => "United States", "code" => "USA", "active" => true],
            ["name" => "Uruguay", "code" => "URY", "active" => true],
            ["name" => "Uzbekistan", "code" => "UZB", "active" => true],
            ["name" => "Vanuatu", "code" => "VUT", "active" => true],
            ["name" => "Vatican City", "code" => "VAT", "active" => true],
            ["name" => "Venezuela", "code" => "VEN", "active" => true],
            ["name" => "Vietnam", "code" => "VNM", "active" => true],
            ["name" => "Wake Island", "code" => "WAK", "active" => true],
            ["name" => "Wallis and Futuna", "code" => "WLF", "active" => true],
            ["name" => "Western Sahara", "code" => "ESH", "active" => true],
            ["name" => "Yemen", "code" => "YEM", "active" => true],
            ["name" => "Zambia", "code" => "ZMB", "active" => true],
            ["name" => "Zimbabwe", "code" => "ZWE", "active" => true],
            ["name" => "Åland Islands", "code" => "ALA", "active" => true]
            ];

        foreach ($countries as $index => $data) {
            DB::table('countries')->updateOrInsert(
                ['slug' => Str::slug($data['name'])],
                [
                    'name' => trim($data['name']),
                    'is_active' => $data['active'],
                    'slug' => Str::slug($data['name']),
                    'code' => $data['code'],
                    'sort_order' => $index + 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
