<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        $nationalities = [
            ["name" => "Afghanistan", "active" => true],
            ["name" => "Albania", "active" => true],
            ["name" => "Algeria", "active" => true],
            ["name" => "American Samoa", "active" => true],
            ["name" => "Andorra", "active" => true],
            ["name" => "Angola", "active" => true],
            ["name" => "Anguilla", "active" => true],
            ["name" => "Antarctica", "active" => true],
            ["name" => "Antigua and Barbuda", "active" => true],
            ["name" => "Argentina", "active" => true],
            ["name" => "Armenia", "active" => true],
            ["name" => "Aruba", "active" => true],
            ["name" => "Australia", "active" => true],
            ["name" => "Austria", "active" => true],
            ["name" => "Azerbaijan", "active" => true],
            ["name" => "Bahamas", "active" => true],
            ["name" => "Bahrain", "active" => true],
            ["name" => "Bangladesh", "active" => true],
            ["name" => "Barbados", "active" => true],
            ["name" => "Belarus", "active" => true],
            ["name" => "Belgium", "active" => true],
            ["name" => "Belize", "active" => true],
            ["name" => "Benin", "active" => true],
            ["name" => "Bermuda", "active" => true],
            ["name" => "Bhutan", "active" => true],
            ["name" => "Bolivia", "active" => true],
            ["name" => "Bosnia and Herzegovina", "active" => true],
            ["name" => "Botswana", "active" => true],
            ["name" => "Bouvet Island", "active" => true],
            ["name" => "Brazil", "active" => true],
            ["name" => "British Antarctic Territory", "active" => true],
            ["name" => "British Indian Ocean Territory", "active" => true],
            ["name" => "British Virgin Islands", "active" => true],
            ["name" => "Brunei", "active" => true],
            ["name" => "Bulgaria", "active" => true],
            ["name" => "Burkina Faso", "active" => true],
            ["name" => "Burundi", "active" => true],
            ["name" => "Cambodia", "active" => true],
            ["name" => "Cameroon", "active" => true],
            ["name" => "Canada", "active" => true],
            ["name" => "Canton and Enderbury Islands", "active" => true],
            ["name" => "Cape Verde", "active" => true],
            ["name" => "Cayman Islands", "active" => true],
            ["name" => "Central African Republic", "active" => true],
            ["name" => "Chad", "active" => true],
            ["name" => "Chile", "active" => true],
            ["name" => "China", "active" => true],
            ["name" => "Christmas Island", "active" => true],
            ["name" => "Cocos [Keeling] Islands", "active" => true],
            ["name" => "Colombia", "active" => true],
            ["name" => "Comoros", "active" => true],
            ["name" => "Congo - Brazzaville", "active" => true],
            ["name" => "Congo - Kinshasa", "active" => true],
            ["name" => "Cook Islands", "active" => true],
            ["name" => "Costa Rica", "active" => true],
            ["name" => "Croatia", "active" => true],
            ["name" => "Cuba", "active" => true],
            ["name" => "Curaçao", "active" => true],
            ["name" => "Cyprus", "active" => true],
            ["name" => "Czech Republic", "active" => true],
            ["name" => "Côte d’Ivoire", "active" => true],
            ["name" => "Denmark", "active" => true],
            ["name" => "Djibouti", "active" => true],
            ["name" => "Dominica", "active" => true],
            ["name" => "Dominican Republic", "active" => true],
            ["name" => "Dronning Maud Land", "active" => true],
            ["name" => "Ecuador", "active" => true],
            ["name" => "Egypt", "active" => true],
            ["name" => "El Salvador", "active" => true],
            ["name" => "Equatorial Guinea", "active" => true],
            ["name" => "Eritrea", "active" => true],
            ["name" => "Estonia", "active" => true],
            ["name" => "Ethiopia", "active" => true],
            ["name" => "Falkland Islands", "active" => true],
            ["name" => "Faroe Islands", "active" => true],
            ["name" => "Fiji", "active" => true],
            ["name" => "Finland", "active" => true],
            ["name" => "France", "active" => true],
            ["name" => "French Guiana", "active" => true],
            ["name" => "French Polynesia", "active" => true],
            ["name" => "French Southern Territories", "active" => true],
            ["name" => "French Southern and Antarctic Territories", "active" => true],
            ["name" => "Gabon", "active" => true],
            ["name" => "Gambia", "active" => true],
            ["name" => "Georgia", "active" => true],
            ["name" => "Germany", "active" => true],
            ["name" => "Ghana", "active" => true],
            ["name" => "Gibraltar", "active" => true],
            ["name" => "Greece", "active" => true],
            ["name" => "Greenland", "active" => true],
            ["name" => "Grenada", "active" => true],
            ["name" => "Guadeloupe", "active" => true],
            ["name" => "Guam", "active" => true],
            ["name" => "Guatemala", "active" => true],
            ["name" => "Guernsey", "active" => true],
            ["name" => "Guinea", "active" => true],
            ["name" => "Guinea-Bissau", "active" => true],
            ["name" => "Guyana", "active" => true],
            ["name" => "Haiti", "active" => true],
            ["name" => "Heard Island and McDonald Islands", "active" => true],
            ["name" => "Honduras", "active" => true],
            ["name" => "Hong Kong SAR China", "active" => true],
            ["name" => "Hungary", "active" => true],
            ["name" => "Iceland", "active" => true],
            ["name" => "India", "active" => true],
            ["name" => "Indonesia", "active" => true],
            ["name" => "Iran", "active" => true],
            ["name" => "Iraq", "active" => true],
            ["name" => "Ireland", "active" => true],
            ["name" => "Isle of Man", "active" => true],
            ["name" => "Israel", "active" => true],
            ["name" => "Italy", "active" => true],
            ["name" => "Jamaica", "active" => true],
            ["name" => "Japan", "active" => true],
            ["name" => "Jersey", "active" => true],
            ["name" => "Johnston Island", "active" => true],
            ["name" => "Jordan", "active" => true],
            ["name" => "Kazakhstan", "active" => true],
            ["name" => "Kenya", "active" => true],
            ["name" => "Kiribati", "active" => true],
            ["name" => "Kuwait", "active" => true],
            ["name" => "Kyrgyzstan", "active" => true],
            ["name" => "Laos", "active" => true],
            ["name" => "Latvia", "active" => true],
            ["name" => "Lebanon", "active" => true],
            ["name" => "Lesotho", "active" => true],
            ["name" => "Liberia", "active" => true],
            ["name" => "Libya", "active" => true],
            ["name" => "Liechtenstein", "active" => true],
            ["name" => "Lithuania", "active" => true],
            ["name" => "Luxembourg", "active" => true],
            ["name" => "Macau SAR China", "active" => true],
            ["name" => "Macedonia", "active" => true],
            ["name" => "Madagascar", "active" => true],
            ["name" => "Malawi", "active" => true],
            ["name" => "Malaysia", "active" => true],
            ["name" => "Maldives", "active" => true],
            ["name" => "Mali", "active" => true],
            ["name" => "Malta", "active" => true],
            ["name" => "Marshall Islands", "active" => true],
            ["name" => "Martinique", "active" => true],
            ["name" => "Mauritania", "active" => true],
            ["name" => "Mauritius", "active" => true],
            ["name" => "Mayotte", "active" => true],
            ["name" => "Metropolitan France", "active" => true],
            ["name" => "Mexico", "active" => true],
            ["name" => "Micronesia", "active" => true],
            ["name" => "Midway Islands", "active" => true],
            ["name" => "Moldova", "active" => true],
            ["name" => "Monaco", "active" => true],
            ["name" => "Mongolia", "active" => true],
            ["name" => "Montenegro", "active" => true],
            ["name" => "Montserrat", "active" => true],
            ["name" => "Morocco", "active" => true],
            ["name" => "Mozambique", "active" => true],
            ["name" => "Myanmar [Burma]", "active" => true],
            ["name" => "Namibia", "active" => true],
            ["name" => "Nauru", "active" => true],
            ["name" => "Nepal", "active" => true],
            ["name" => "Netherlands", "active" => true],
            ["name" => "Netherlands Antilles", "active" => true],
            ["name" => "Neutral Zone", "active" => true],
            ["name" => "New Caledonia", "active" => true],
            ["name" => "New Zealand", "active" => true],
            ["name" => "Nicaragua", "active" => true],
            ["name" => "Niger", "active" => true],
            ["name" => "Nigeria", "active" => true],
            ["name" => "Niue", "active" => true],
            ["name" => "Norfolk Island", "active" => true],
            ["name" => "North Korea", "active" => true],
            ["name" => "North Vietnam", "active" => true],
            ["name" => "Northern Mariana Islands", "active" => true],
            ["name" => "Norway", "active" => true],
            ["name" => "Oman", "active" => true],
            ["name" => "Other", "active" => false],
            ["name" => "Pacific Islands Trust Territory", "active" => true],
            ["name" => "Pakistan", "active" => true],
            ["name" => "Palau", "active" => true],
            ["name" => "Palestinian Territories", "active" => true],
            ["name" => "Panama", "active" => true],
            ["name" => "Panama Canal Zone", "active" => true],
            ["name" => "Papua New Guinea", "active" => true],
            ["name" => "Paraguay", "active" => true],
            ["name" => "Peru", "active" => true],
            ["name" => "Philippines", "active" => true],
            ["name" => "Pitcairn Islands", "active" => true],
            ["name" => "Poland", "active" => true],
            ["name" => "Portugal", "active" => true],
            ["name" => "Puerto Rico", "active" => true],
            ["name" => "Qatar", "active" => true],
            ["name" => "Romania", "active" => true],
            ["name" => "Russia", "active" => true],
            ["name" => "Rwanda", "active" => true],
            ["name" => "Réunion", "active" => true],
            ["name" => "Saint Barthélemy", "active" => true],
            ["name" => "Saint Helena", "active" => true],
            ["name" => "Saint Kitts and Nevis", "active" => true],
            ["name" => "Saint Lucia", "active" => true],
            ["name" => "Saint Martin", "active" => true],
            ["name" => "Saint Pierre and Miquelon", "active" => true],
            ["name" => "Saint Vincent and the Grenadines", "active" => true],
            ["name" => "Samoa", "active" => true],
            ["name" => "San Marino", "active" => true],
            ["name" => "Saudi Arabia", "active" => true],
            ["name" => "Senegal", "active" => true],
            ["name" => "Serbia", "active" => true],
            ["name" => "Serbia and Montenegro", "active" => true],
            ["name" => "Seychelles", "active" => true],
            ["name" => "Sierra Leone", "active" => true],
            ["name" => "Singapore", "active" => true],
            ["name" => "Slovakia", "active" => true],
            ["name" => "Slovenia", "active" => true],
            ["name" => "Solomon Islands", "active" => true],
            ["name" => "Somalia", "active" => true],
            ["name" => "South Africa", "active" => true],
            ["name" => "South Georgia and the South Sandwich Islands", "active" => true],
            ["name" => "South Korea", "active" => true],
            ["name" => "Spain", "active" => true],
            ["name" => "Sri Lanka", "active" => true],
            ["name" => "Sudan", "active" => true],
            ["name" => "Suriname", "active" => true],
            ["name" => "Svalbard and Jan Mayen", "active" => true],
            ["name" => "Swaziland", "active" => true],
            ["name" => "Sweden", "active" => true],
            ["name" => "Switzerland", "active" => true],
            ["name" => "Syria", "active" => true],
            ["name" => "São Tomé and Príncipe", "active" => true],
            ["name" => "Taiwan", "active" => true],
            ["name" => "Tajikistan", "active" => true],
            ["name" => "Tanzania", "active" => true],
            ["name" => "Thailand", "active" => true],
            ["name" => "Timor-Leste", "active" => true],
            ["name" => "Togo", "active" => true],
            ["name" => "Tokelau", "active" => true],
            ["name" => "Tonga", "active" => true],
            ["name" => "Trinidad and Tobago", "active" => true],
            ["name" => "Tunisia", "active" => true],
            ["name" => "Turkey", "active" => true],
            ["name" => "Turkmenistan", "active" => true],
            ["name" => "Turks and Caicos Islands", "active" => true],
            ["name" => "Tuvalu", "active" => true],
            ["name" => "U.S. Minor Outlying Islands", "active" => true],
            ["name" => "U.S. Miscellaneous Pacific Islands", "active" => true],
            ["name" => "U.S. Virgin Islands", "active" => true],
            ["name" => "Uganda", "active" => true],
            ["name" => "Ukraine", "active" => true],
            ["name" => "Union of Soviet Socialist Republics", "active" => true],
            ["name" => "United Arab Emirates", "active" => true],
            ["name" => "United Kingdom", "active" => true],
            ["name" => "United States", "active" => true],
            ["name" => "Uruguay", "active" => true],
            ["name" => "Uzbekistan", "active" => true],
            ["name" => "Vanuatu", "active" => true],
            ["name" => "Vatican City", "active" => true],
            ["name" => "Venezuela", "active" => true],
            ["name" => "Vietnam", "active" => true],
            ["name" => "Wake Island", "active" => true],
            ["name" => "Wallis and Futuna", "active" => true],
            ["name" => "Western Sahara", "active" => true],
            ["name" => "Yemen", "active" => true],
            ["name" => "Zambia", "active" => true],
            ["name" => "Zimbabwe", "active" => true],
            ["name" => "Åland Islands", "active" => true]
        ];

        foreach ($nationalities as $data) {
            DB::table('nationalities')->updateOrInsert(
                ['slug' => Str::slug($data['name'])], // Check by slug
                [
                    'name' => trim($data['name']),
                    'is_active' => $data['active'],
                    'slug' => Str::slug($data['name']),
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
