<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Usage: php artisan db:seed --class=SettingsSeeder
     */
    public function run(): void
    {
        $settings = [
            // Teacher Settings
            [
                'group' => 'teacher',
                'key' => 'teacher_default_password',
                'value' => 'pass@123456',
                'type' => 'string',
                'label' => 'Default Teacher Password',
                'description' => 'Default password for newly created teacher accounts',
                'is_public' => false,
                'sort_order' => 1,
            ],
            [
                'group' => 'teacher',
                'key' => 'teacher_send_welcome_email',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Send Welcome Email',
                'description' => 'Send login credentials email when teacher account is created',
                'is_public' => false,
                'sort_order' => 2,
            ],
            // System Settings
            [
                'group' => 'system',
                'key' => 'check_package_updates',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Check Package Updates',
                'description' => 'Enable checking for latest package versions on dashboard',
                'is_public' => false,
                'sort_order' => 3,
            ],
            // Mail Configuration
            [
                'group' => 'system',
                'key' => 'mail_mailer',
                'value' => 'smtp',
                'type' => 'string',
                'label' => 'Mailer',
                'description' => 'Mail driver (smtp, log)',
                'is_public' => false,
                'sort_order' => 10,
            ],
            [
                'group' => 'system',
                'key' => 'mail_host',
                'value' => 'smtp.gmail.com',
                'type' => 'string',
                'label' => 'Mail Host',
                'description' => 'SMTP Host',
                'is_public' => false,
                'sort_order' => 11,
            ],
            [
                'group' => 'system',
                'key' => 'mail_port',
                'value' => '587',
                'type' => 'integer',
                'label' => 'Mail Port',
                'description' => 'SMTP Port',
                'is_public' => false,
                'sort_order' => 12,
            ],
            [
                'group' => 'system',
                'key' => 'mail_username',
                'value' => '',
                'type' => 'string',
                'label' => 'Mail Username',
                'description' => 'SMTP Username',
                'is_public' => false,
                'sort_order' => 13,
            ],
            [
                'group' => 'system',
                'key' => 'mail_password',
                'value' => '',
                'type' => 'string',
                'label' => 'Mail Password',
                'description' => 'SMTP Password',
                'is_public' => false,
                'sort_order' => 14,
            ],
            [
                'group' => 'system',
                'key' => 'mail_encryption',
                'value' => 'tls',
                'type' => 'string',
                'label' => 'Mail Encryption',
                'description' => 'SMTP Encryption',
                'is_public' => false,
                'sort_order' => 15,
            ],
            [
                'group' => 'system',
                'key' => 'mail_from_address',
                'value' => 'hello@example.com',
                'type' => 'string',
                'label' => 'From Address',
                'description' => 'Global From Address',
                'is_public' => false,
                'sort_order' => 16,
            ],
            [
                'group' => 'system',
                'key' => 'mail_from_name',
                'value' => 'FMS',
                'type' => 'string',
                'label' => 'From Name',
                'description' => 'Global From Name',
                'is_public' => false,
                'sort_order' => 17,
            ],
            // Teacher Integration Settings
            [
                'group' => 'teacher_integration',
                'key' => 'teacher_integration_api_url',
                'value' => 'http://localhost:8000/api/v1/teachers/preview',
                'type' => 'string',
                'label' => 'Teacher Integration API URL',
                'description' => 'API endpoint URL for searching and previewing teacher profiles',
                'is_public' => false,
                'sort_order' => 20,
            ],
            [
                'group' => 'teacher_integration',
                'key' => 'teacher_integration_mapping',
                'value' => 'erp_teacher_profile',
                'type' => 'string',
                'label' => 'Teacher Integration Mapping Slug',
                'description' => 'Mapping configuration slug used for transforming teacher JSON',
                'is_public' => false,
                'sort_order' => 21,
            ],
            // Profile Integrity & Threshold Settings
            [
                'group' => 'profile_integrity',
                'key' => 'profile_mandatory_weight',
                'value' => '80',
                'type' => 'integer',
                'label' => 'Mandatory Fields Weight (%)',
                'description' => 'Weight allocated to essential fields',
                'is_public' => true,
                'sort_order' => 30,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_optional_weight',
                'value' => '20',
                'type' => 'integer',
                'label' => 'Optional Fields Weight (%)',
                'description' => 'Weight allocated to optional enrichment fields',
                'is_public' => true,
                'sort_order' => 31,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_enable_relative_benchmark',
                'value' => 'false',
                'type' => 'boolean',
                'label' => 'Enable Relative Peer Benchmark',
                'description' => 'Enable dynamic peer benchmark scaling based on top performing faculty',
                'is_public' => true,
                'sort_order' => 32,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_pub_tier1_count',
                'value' => '3',
                'type' => 'integer',
                'label' => 'Publications Tier 1 (50% Credit)',
                'description' => 'Publication count for Tier 1 credit',
                'is_public' => true,
                'sort_order' => 33,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_pub_tier2_count',
                'value' => '5',
                'type' => 'integer',
                'label' => 'Publications Tier 2 (80% Credit)',
                'description' => 'Publication count for Tier 2 credit',
                'is_public' => true,
                'sort_order' => 34,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_pub_tier3_count',
                'value' => '10',
                'type' => 'integer',
                'label' => 'Publications Tier 3 (100% Credit)',
                'description' => 'Publication count for Tier 3 credit',
                'is_public' => true,
                'sort_order' => 35,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_award_tier1_count',
                'value' => '1',
                'type' => 'integer',
                'label' => 'Awards Tier 1 (50% Credit)',
                'description' => 'Awards count for Tier 1 credit',
                'is_public' => true,
                'sort_order' => 36,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_award_tier2_count',
                'value' => '2',
                'type' => 'integer',
                'label' => 'Awards Tier 2 (80% Credit)',
                'description' => 'Awards count for Tier 2 credit',
                'is_public' => true,
                'sort_order' => 37,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_award_tier3_count',
                'value' => '3',
                'type' => 'integer',
                'label' => 'Awards Tier 3 (100% Credit)',
                'description' => 'Awards count for Tier 3 credit',
                'is_public' => true,
                'sort_order' => 38,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_training_tier1_count',
                'value' => '1',
                'type' => 'integer',
                'label' => 'Training Tier 1 (50% Credit)',
                'description' => 'Training count for Tier 1 credit',
                'is_public' => true,
                'sort_order' => 39,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_training_tier2_count',
                'value' => '2',
                'type' => 'integer',
                'label' => 'Training Tier 2 (80% Credit)',
                'description' => 'Training count for Tier 2 credit',
                'is_public' => true,
                'sort_order' => 40,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_training_tier3_count',
                'value' => '3',
                'type' => 'integer',
                'label' => 'Training Tier 3 (100% Credit)',
                'description' => 'Training count for Tier 3 credit',
                'is_public' => true,
                'sort_order' => 41,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_min_skills',
                'value' => '3',
                'type' => 'integer',
                'label' => 'Minimum Skills Count',
                'description' => 'Minimum skills required for 100% credit',
                'is_public' => true,
                'sort_order' => 42,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_min_teaching_areas',
                'value' => '2',
                'type' => 'integer',
                'label' => 'Minimum Teaching Areas Count',
                'description' => 'Minimum teaching areas required for 100% credit',
                'is_public' => true,
                'sort_order' => 43,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'profile_min_social_links',
                'value' => '2',
                'type' => 'integer',
                'label' => 'Minimum Social Links Count',
                'description' => 'Minimum social links required for 100% credit',
                'is_public' => true,
                'sort_order' => 44,
            ],
            // Section Weights (13 Profile Tabs)
            [
                'group' => 'profile_integrity',
                'key' => 'weight_basic',
                'value' => '8',
                'type' => 'integer',
                'label' => 'Basic Info Weight',
                'description' => 'Percentage weight for Basic Info',
                'is_public' => true,
                'sort_order' => 50,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_contact',
                'value' => '8',
                'type' => 'integer',
                'label' => 'Contact Info Weight',
                'description' => 'Percentage weight for Contact Info',
                'is_public' => true,
                'sort_order' => 51,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_personal',
                'value' => '6',
                'type' => 'integer',
                'label' => 'Personal Details Weight',
                'description' => 'Percentage weight for Personal Details',
                'is_public' => true,
                'sort_order' => 52,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_academic_info',
                'value' => '5',
                'type' => 'integer',
                'label' => 'Academic Info Weight',
                'description' => 'Percentage weight for Academic Info',
                'is_public' => true,
                'sort_order' => 53,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_education',
                'value' => '18',
                'type' => 'integer',
                'label' => 'Academic Qualification Weight',
                'description' => 'Percentage weight for Education',
                'is_public' => true,
                'sort_order' => 54,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_publication',
                'value' => '15',
                'type' => 'integer',
                'label' => 'Publications Weight',
                'description' => 'Percentage weight for Publications',
                'is_public' => true,
                'sort_order' => 55,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_experience',
                'value' => '12',
                'type' => 'integer',
                'label' => 'Job Experience Weight',
                'description' => 'Percentage weight for Job Experience',
                'is_public' => true,
                'sort_order' => 56,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_training',
                'value' => '7',
                'type' => 'integer',
                'label' => 'Training Experience Weight',
                'description' => 'Percentage weight for Training Experience',
                'is_public' => true,
                'sort_order' => 57,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_award',
                'value' => '5',
                'type' => 'integer',
                'label' => 'Awards & Honors Weight',
                'description' => 'Percentage weight for Awards & Honors',
                'is_public' => true,
                'sort_order' => 58,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_skill',
                'value' => '6',
                'type' => 'integer',
                'label' => 'Skills & Expertise Weight',
                'description' => 'Percentage weight for Skills & Expertise',
                'is_public' => true,
                'sort_order' => 59,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_teaching',
                'value' => '5',
                'type' => 'integer',
                'label' => 'Teaching Areas Weight',
                'description' => 'Percentage weight for Teaching Areas',
                'is_public' => true,
                'sort_order' => 60,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_membership',
                'value' => '3',
                'type' => 'integer',
                'label' => 'Memberships Weight',
                'description' => 'Percentage weight for Memberships',
                'is_public' => true,
                'sort_order' => 61,
            ],
            [
                'group' => 'profile_integrity',
                'key' => 'weight_social',
                'value' => '2',
                'type' => 'integer',
                'label' => 'Social Links Weight',
                'description' => 'Percentage weight for Social Links',
                'is_public' => true,
                'sort_order' => 62,
            ],
        ];

        foreach ($settings as $setting) {
            // Use updateOrInsert to avoid duplicates
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('Settings seeded successfully.');
    }
}
